databases:
  - name: pg
    databaseName: railsdb_14v9
    user: admin
    region: singapore

services:
  - type: web
    name: task-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false